/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2021-03-17 15:37:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj3.dto.TimeTableDTO;
import in.co.rays.proj3.ctl.TimeTableCtl;
import java.util.List;
import in.co.rays.proj3.util.HTMLUtility;
import java.util.HashMap;
import in.co.rays.proj3.util.DataUtility;
import in.co.rays.proj3.util.ServletUtility;
import in.co.rays.proj3.dto.RoleDTO;
import in.co.rays.proj3.ctl.LoginCtl;
import in.co.rays.proj3.dto.UserDTO;
import in.co.rays.proj3.ctl.ORSView;
import java.util.Calendar;
import java.util.Calendar;

public final class TimeTableView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1610465422798L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1615957447311L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.proj3.ctl.LoginCtl");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("in.co.rays.proj3.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.proj3.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.proj3.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.proj3.ctl.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj3.dto.TimeTableDTO");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.proj3.dto.UserDTO");
    _jspx_imports_classes.add("in.co.rays.proj3.ctl.TimeTableCtl");
    _jspx_imports_classes.add("in.co.rays.proj3.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorView.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Time Table View</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(\"/project3/image/add.jpg\");\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-attachment: fixed;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error_msg{\r\n");
      out.write("margin-left: -110px; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"");
      out.print(ORSView.TIME_TABLE_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<title></title>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- for Jquery Calander  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/project3/css/jquery-ui.css\">\r\n");
      out.write("<script src=\"/project3/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/project3/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/project3/js/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/project3/js/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\">\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap end -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/project3/css/jquery-ui.css\">\r\n");
      out.write("<script src=\"/project3/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/project3/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/project3/js/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#dcolor {\r\n");
      out.write("\tfont-size: 110%;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\tbackground: lightseagreen;\r\n");
      out.write("\tbox-shadow: 0 0 1px #ccc;\r\n");
      out.write("\t-webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("\t-webkit-transform: scale(1.1);\r\n");
      out.write("\tbackground: #31708f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-success {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\tbox-shadow: 0 0 1px #ccc;\r\n");
      out.write("\t-webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-success:hover {\r\n");
      out.write("\t-webkit-transform: scale(1.1);\r\n");
      out.write("\tbackground: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-info {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\tbox-shadow: 0 0 1px #ccc;\r\n");
      out.write("\t-webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-info:hover {\r\n");
      out.write("\t-webkit-transform: scale(1.1);\r\n");
      out.write("\tbackground: #33d6ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-warning {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\tbox-shadow: 0 0 1px #ccc;\r\n");
      out.write("\t-webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-warning:hover {\r\n");
      out.write("\t-webkit-transform: scale(1.1);\r\n");
      out.write("\tbackground: #ff9933;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-danger {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\tbox-shadow: 0 0 1px #ccc;\r\n");
      out.write("\t-webkit-transition: all 0.5s ease-in-out;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-danger:hover {\r\n");
      out.write("\t-webkit-transform: scale(1.1);\r\n");
      out.write("\tbackground: #ff3333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel {\r\n");
      out.write("\tbox-shadow: 9px 8px 7px #001a33;\r\n");
      out.write("\tbackground: rgba(10, 10, 10, 0.44);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-primary {\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-danger {\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("\tcolor: #ff0000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("\tbordercolor: blue;\r\n");
      out.write("\tbackground-color: #9999ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse {\r\n");
      out.write("\t/*  background-color: #7986CB ; */\r\n");
      out.write("\tborder-color: black;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\t/*  background-image: url(\"img/images (2)navar00.jpg\");  */\r\n");
      out.write("\tbackground: #001a33;\r\n");
      out.write("\tbackground-repeat:;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("element.style {\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tpadding-top: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top {\r\n");
      out.write("\tmargin-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".glyphicon-edit {\r\n");
      out.write("\tcolor: #800000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel>.panel-heading {\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tbackground: rgba(10, 10, 10, 0.44);\r\n");
      out.write("\tcolor: #993333;\r\n");
      out.write("\tfont-family: cursive;\r\n");
      out.write("\t/* margin-right:30px; */\r\n");
      out.write("\t/* \tbackground: rgba(10, 10, 10, 0.44);\r\n");
      out.write(" */\r\n");
      out.write("\tbackground-size: appworkspace;\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("\tbackground-color: #dedfe2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-heading {\r\n");
      out.write("\tbackground-color: #060613;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#error {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tposition: center;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#success {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tposition: center;\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction selectAll(source) {\r\n");
      out.write("\t\tcheckboxes = document.getElementsByName('ids');\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = 0, n = checkboxes.length; i < n; i++) {\r\n");
      out.write("\t\t\tcheckboxes[i].checked = source.checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('[name=\"ids\"]').click(function() {\r\n");
      out.write("\t\t\tif (!($(this)[0].checked)) {\r\n");
      out.write("\t\t\t\t$('[onclick=\"selectAll(this)\"]')[0].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t;\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".dropdown\").hover(function() {\r\n");
      out.write("\t\t\t$('.dropdown-menu', this).stop(true, true).fadeIn(\"fast\");\r\n");
      out.write("\t\t\t$(this).toggleClass('open');\r\n");
      out.write("\t\t}, function() {\r\n");
      out.write("\t\t\t$('.dropdown-menu', this).stop(true, true).fadeOut(\"fast\");\r\n");
      out.write("\t\t\t$(this).toggleClass('open');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#datepicker\").datepicker({\r\n");
      out.write("\t\t\tchangeMonth : true,\r\n");
      out.write("\t\t\tchangeYear : true,\r\n");
      out.write("\t\t\tdateFormat : 'mm/dd/yy',\r\n");
      out.write("\t\t\tyearRange:\"-57:-18\",\r\n");
      out.write("\t\t\tdefaultDate : \"01/01/2000\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#datesun\").datepicker({\r\n");
      out.write("\t\t\t beforeShowDay:\r\n");
      out.write("\t\t\t\tfunction(dt){\r\n");
      out.write("\t\t\t\treturn[dt.getDay()==0 ? false:true]     ///// to disable sunday\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\t\t\tchangeMonth:true,\r\n");
      out.write("\t\t\tchangeYear:true,\r\n");
      out.write("\t\t\tstepMonths: 12,\r\n");
      out.write("\t\t\tyearRange:'+0:+5',\r\n");
      out.write("\t\t\t//yearRange:\"+10:\"\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#datefac\").datepicker({\r\n");
      out.write("\t\t\t beforeShowDay:\r\n");
      out.write("\t\t\t\tfunction(dt){\r\n");
      out.write("\t\t\t\treturn[dt.getDay()==0 ? false:true]     ///// to disable sunday\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\t\t\tchangeMonth:true,\r\n");
      out.write("\t\t\tchangeYear:true,\r\n");
      out.write("\t\t\tyearRange:\"-57:+0\",\t\r\n");
      out.write("\t\t\tdefaultDate:\"01/01/2018\"\r\n");
      out.write("\t\t\t//defaultDate:\"01/01/1999\"\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("    function selectAll(source) {\r\n");
      out.write("    \tcheckboxes = document.getElementsByName('ids');\r\n");
      out.write("    \tfor (var i = 0, n = checkboxes.length; i < n; i++) {\r\n");
      out.write("    \t\tcheckboxes[i].checked = source.checked;\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function selectone(so) {\r\n");
      out.write("    \tcheckboxes = document.getElementById('mainbox');\r\n");
      out.write("    \tunbox = document.getElementsByName('ids');\r\n");
      out.write("    \tvar box = false;\r\n");
      out.write("    \tfor (var i = 0, n = unbox.length; i < n; i++) {\r\n");
      out.write("    \t\tif (unbox[i].checked == true) {\r\n");
      out.write("    \t\t\tbox = true;\r\n");
      out.write("    \t\t} else {\r\n");
      out.write("    \t\t\tbox = false;\r\n");
      out.write("    \t\t\tbreak;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \tcheckboxes.checked = box;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" style=\"background-color: rgba(28, 35, 49, 0.6);\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-left\" style=\"background-color: #3030358f\">\r\n");
      out.write("\t\t\t\t<img src=\"/project3/image/download.png\" width=\"130\" height=\"52\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"  id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t>&emsp;<span class=\"glyphicon glyphicon-home\" style=\" padding-right: 10px\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\" style=\"background:\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						UserDTO userdto = (UserDTO) session.getAttribute("user");
						if (userdto == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='block'\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: auto; font-family: cursive; color: #e0ebeb;\"><span class=\"glyphicon glyphicon-log-in\" style=\"font-size:20px;margin-right: 8px;\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\" id=\"dcolor\">\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-family: cursive; color: #e0ebeb\"> <span class=\"glyphicon glyphicon-user\" style=\"font-size:20px;margin-right: 10px;\"></span>Register\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown role=\"\r\n");
      out.write("\t\t\t\t\t\tbutton\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"><span\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></span><b> <span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\" \r\n");
      out.write("        \t\tstyle=\"font-size:18px;margin-right: 3px;\"></span>");

 						if (userdto != null) {
 						
      out.write(" Hello, ");
      out.print(userdto.getFirstName());
      out.write('(');
      out.print(session.getAttribute("role"));
      out.write(")<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></span> ");

 						}
 						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</b></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-edit\" aria-hidden=\"true\"></span> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Edit Profile</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-cog\" style=\"color: #0f0f0a\"></span> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Change Password</b></font>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\" target=\"blank\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-file\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: #734d26\"></span> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Java Doc</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=logout\"><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive; color: #800000;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Logout</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					UserDTO user1 = (UserDTO) session.getAttribute("user");
					if (user1 != null) {
						if (userdto.getRoleId() == 1) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav \">\r\n");
      out.write("\t\t\t\t\t<li></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">User<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\" style=\"color: #990000\"></span> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Add User</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>User List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Role<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>Add Role</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Role List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Student<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Add Student</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Student List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">College<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>Add College</b></font>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>College List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Marksheet <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Get Marksheet</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>Add Marksheet</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Marksheet List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>Marksheet Merit\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList</b></font> </a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Faculty<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=");
      out.print(ORSView.FACULTY_CTL);
      out.write("><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Add Faculty</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Faculty List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Course<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Add Course</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"> <b>Course List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Subject<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Add Subject</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Subject List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Time Table<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.TIME_TABLE_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-education\" style=\"color: #993366\"></span><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b> Add Time Table</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.TIME_TABLE_LIST_CTL);
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\" style=\"color: #734d26\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"font-family: cursive;\"><b>Time Table List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div> ");

 	}
 		if (userdto.getRoleId() == 2) {
 
      out.write("<ul class=\"nav navbar-nav \">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Course<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Course List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Subject<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>Subject List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" id=\"dcolor\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">TimeTable<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.TIME_TABLE_LIST_CTL);
      out.write("\"><font\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-family: cursive;\"><b>TimeTable List</b></font></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul> ");

 	}
 		if (userdto.getRoleId() == 5) {
 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav navbar-nav \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Marksheet <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tMerit List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tMarksheet</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tList</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"dcolor\" data-toggle=\"dropdown\" href=\"#\">Course<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tList</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"dcolor\" data-toggle=\"dropdown\" href=\"#\">Subject<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"background-color: wheat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tList</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul> ");

 	}
 	}
 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"./js/calendar.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      in.co.rays.proj3.dto.TimeTableDTO dto = null;
      dto = (in.co.rays.proj3.dto.TimeTableDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.proj3.dto.TimeTableDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<center  style=\"height: 360px;\">\r\n");
      out.write("\t\t\t");

				List cList = (List) request.getAttribute("courseList");
				List sList = (List) request.getAttribute("subjectList");
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">      \r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-md-6 col-sm-12 col-md-offset-3\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-primary\" style=\"margin-top:10px; background-color:  #DCDCDC;\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\" style=\"background-color: #e9967a00;\" align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

 	if (dto.getId() > 0) {
 
      out.write(" <b><h1>Update Time Table</h1></b> ");

 	} else {
 
      out.write(" <b><h1>Add Time Table</h1></b> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"alert alert-success\" role=\"alert\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 90%; margin-left: 0%; font-size: 150%\"\r\n");
      out.write("\t\t\t\t");
      out.print(ServletUtility.getSuccessMessage(request).equals("") ? "hidden" : "");
      out.write(">\r\n");
      out.write("\t\t\t\t<b> ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</b>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"alert alert-danger\" role=\"alert\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 90%; margin-left: 0%; font-size: 150%;\"\r\n");
      out.write("\t\t\t\t");
      out.print(ServletUtility.getErrorMessage(request).equals("") ? "hidden" : "");
      out.write(">\r\n");
      out.write("\t\t\t\t<b>");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</b>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(dto.getId());
      out.write("\"> \r\n");
      out.write("\t\t<input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(dto.getCreatedBy());
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"modifiedBy\" value=\"");
      out.print(dto.getModifiedBy());
      out.write("\"> \r\n");
      out.write("\t\t<input type=\"hidden\" name=\"createdDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(dto.getCreatedDatetime()));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(dto.getModifiedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t <div class=\"col-xs-12 col-sm-12 col-md-10 col-lg-12\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t<div class=\"form-group\" style=\"margin-left: 10%;\">\r\n");
      out.write("\t\t<label align=\"left\" class=\"control-label col-md-6 text-info\">\r\n");
      out.write("\t\tCourse Name<span style=\"color: red;\">*</span></label>\r\n");
      out.write("\r\n");
      out.write("\t\t <div class=\"col-md-12\"  style=\"margin-bottom: 25px;\">\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t<span class=\"input-group-addon\">\r\n");
      out.write("\t\t<i class=\"glyphicon glyphicon-user\"></i></span> \r\n");
      out.write("\t\t");
      out.print(HTMLUtility.getList("courseId", String.valueOf(dto.getCourseId()), cList));
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<label class=\"control-label text-danger error_msg\" for=\"inputError1\">\r\n");
      out.write("\t\t");
      out.print(ServletUtility.getErrorMessage("courseId", request));
      out.write("</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\" style=\"margin-left: 10%;\">\r\n");
      out.write("\t\t<label align=\"left\" class=\"control-label col-md-6 text-info\">\r\n");
      out.write("\t\tSubject Name<span style=\"color: red;\">*</span></label>\r\n");
      out.write("\r\n");
      out.write("\t\t <div class=\"col-md-12\"  style=\"margin-bottom: 25px;\">\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t<span class=\"input-group-addon\">\r\n");
      out.write("\t\t<i class=\"glyphicon glyphicon-user\"></i></span> \r\n");
      out.write("\t\t");
      out.print(HTMLUtility.getList("subjectId", String.valueOf(dto.getSubjectId()), sList));
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<label class=\"control-label text-danger  error_msg\" for=\"inputError1\">\r\n");
      out.write("\t\t");
      out.print(ServletUtility.getErrorMessage("subjectId", request));
      out.write("</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label align=\"left\" class=\"control-label col-md-6 text-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tExam Time<span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <div class=\"col-md-12\"  style=\"margin-bottom: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

							HashMap map = new HashMap();
							map.put("","--- Select Time ---");
							map.put("08:00 AM To 10:00 AM", "08:00 AM To 10:00 AM");
							map.put("12:00 PM To 02:00 PM", "12:00 PM To 02:00 PM");
							map.put("03:00 PM To 05:00 PM", "03:00 PM To 05:00 PM");
							String examTimeList = HTMLUtility.getList("examTime", dto.getExamTime(), map);
						
      out.write(' ');
      out.print(examTimeList);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label text-danger  error_msg\" for=\"inputError1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(ServletUtility.getErrorMessage("examTime", request));
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"form-group\" style=\"margin-left: 10%;\">\r\n");
      out.write("\t\t<label align=\"left\" class=\"control-label col-md-6 text-info\">\r\n");
      out.write("\t\tExam Date<span style=\"color: red;\">*</span></label>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t <div class=\"col-md-12\"  style=\"margin-bottom: 25px;\">\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t<span class=\"input-group-addon\">\r\n");
      out.write("\t\t<i class=\"glyphicon glyphicon-calendar\"></i></span> \r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" name=\"examDate\"  id=\"datesun\" readonly=\"readonly\"\r\n");
      out.write("\t\tplaceholder=\"Select Date of Exam\" value=\"");
      out.print(DataUtility.getDateString(dto.getExamDate()));
      out.write("\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<label class=\"control-label text-danger  error_msg\" for=\"inputError1\">\r\n");
      out.write("\t\t");
      out.print(ServletUtility.getErrorMessage("examDate", request));
      out.write("</label>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\" align=\"center\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("\t\t");
if (dto.getId() > 0) { 
      out.write("<br>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\" name=\"operation\"\r\n");
      out.write("\t\tvalue=\"");
      out.print(TimeTableCtl.OP_UPDATE);
      out.write("\"><span class=\"glyphicon glyphicon-check\"></span> Update</button>\r\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-primary\" name=\"operation\"\r\n");
      out.write("\t\tvalue=\"");
      out.print(TimeTableCtl.OP_CANCEL);
      out.write("\"><span class=\"glyphicon glyphicon-remove\"></span> Cancel</button>\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
					
      out.write("<br>\r\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-primary\" name=\"operation\"\r\n");
      out.write("\t\tvalue=\"");
      out.print(TimeTableCtl.OP_SAVE);
      out.write("\"><span class=\"glyphicon glyphicon-check\"></span> Save</button>&emsp;\r\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-warning\" name=\"operation\"\r\n");
      out.write("\t\tvalue=\"");
      out.print(TimeTableCtl.OP_RESET);
      out.write("\"><span class=\"glyphicon glyphicon-refresh\"></span> Reset</button>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"min-height: 200px\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("*, *:before, *:after {\r\n");
      out.write("\tbox-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tmin-height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\tcolor: gainsboro;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\t/*  padding: 0.5rem; */\r\n");
      out.write("\tbox-shadow: 0px 0px 0px 0px #244a4a;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tz-index: 2500;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		Calendar c = Calendar.getInstance();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer\"\r\n");
      out.write("\t\tstyle=\"background-color: rgba(28, 35, 49, 0.85); height: 40px;\">\r\n");
      out.write("\t\t<p style=\"font-size: 16px; padding-top: 10px;\">\r\n");
      out.write("\t\t\tCopyright &copy; ");
      out.print(c.getWeekYear());
      out.write(" RAYS Technologies || <font color=\"wheat\">\r\n");
      out.write("\t\t\t\tDesigned by State pattern</font> </b>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
